#!/usr/bin/env bash

# Source the current hostname if there exists a file called 'hosts' in the current dir
if [ -f ./host ]; then
    source ./host
fi

# Ensure the CURRENTHOST is set
if [ ! -n "$CURRENTHOST" ]; then
    echo "Environment variable CURRENTHOST is not set or empty. You can export it in a file called 'host' in this directory"
    exit 0
fi

nix-collect-garbage && nix-collect-garbage -d && sudo nixos-rebuild boot --flake .#$CURRENTHOST
