#!/usr/bin/env bash

# Source the current hostname if there exists a file called 'hosts' in the current dir
if [ -f ./host ]; then
    source ./host
fi

# Ensure the CURRENTHOST is set
if [ ! -n "$CURRENTHOST" ]; then
    echo "Environment variable CURRENTHOST is not set or empty. You can export it in a file called 'host' in this directory"
    exit 0
fi

# Ensure flake.nix handles this host
grep -q "nixosConfigurations\.${CURRENTHOST}" flake.nix
if [[ ! $? -eq 0 ]]; then
    echo "Hostname: $CURRENTHOST not configured in flake.nix. Aborting..."
    exit 0
fi

# Ensure there is a hardware configuration for CURRENTHOST
if [ ! -f ./hosts/$CURRENTHOST.nix ]; then
    echo "Could not find a hardware configuration file for host: '$CURRENTHOST'... Generating one"
    nixos-generate-config --show-hardware-config > ./hosts/$CURRENTHOST.nix
fi

# Rebuild for this host
echo "Rebuilding for host: $CURRENTHOST"
sudo nixos-rebuild switch --flake .#$CURRENTHOST
