#!/usr/bin/env bash

# Source the current hostname if there exists a file called 'hosts' in the current dir
if [ -f ./host ]; then
    source ./host
fi

export NIXPKGS_ALLOW_INSECURE=1

# Ensure the CURRENTHOST is set
if [ ! -n "$CURRENTHOST" ]; then
    echo "Environment variable CURRENTHOST is not set or empty. You can export it in a file called 'host' in this directory"
    exit 0
fi

# Ensure flake.nix handles this host
grep -q "nixosConfigurations\.${CURRENTHOST}" flake.nix
if [[ ! $? -eq 0 ]]; then
    echo "Hostname: $CURRENTHOST not configured in flake.nix. Aborting..."
    exit 0
fi

# Ensure there is a hardware configuration for CURRENTHOST
if [ ! -f ./hosts/$CURRENTHOST.nix ]; then
    echo "Could not find a hardware configuration file for host: '$CURRENTHOST'... Generating one"
    nixos-generate-config --show-hardware-config > ./hosts/$CURRENTHOST.nix
fi

# Home manager is fucken stupid. Just delete the backups it makes
rm $HOME/.gtkrc-2.0.backup 2>/dev/null

# Rebuild for this host
echo "Rebuilding for host: $CURRENTHOST"

sudo nixos-rebuild \
    --option extra-substituters https://install.determinate.systems \
    --option extra-trusted-public-keys cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= \
    switch --flake .#$CURRENTHOST --impure 
